<?php
$title = 'File Upload';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('upload', array('action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo '<br />';
echo $this->formRow($form->get('fileupload'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();