<?php echo $this->doctype(); 
use Zend\Session\Container;

$session = new Container('userData');
$userId = $session->userId;
$role = $session->role;
if((!($_SERVER['REQUEST_URI'] == '/login')) && (!($userId))){ ?>
    <script type="text/javascript">
        window.location = "/login"
    </script>
<?php } ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->appendStylesheet($this->basePath() . '/css/print.css', 'print');

        
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>

    </head>
    <body>
        <div class="container">
            <div class="navbar">
                <a class="brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/THG_Logo.jpg') ?>" /></a>
                <h1>RevCast</h1>
                <?php if(!($_SERVER['REQUEST_URI'] == '/login')){ ?>
                <div id='cssmenu'>
                    <ul>
                       <li><a href='/welcome'><span>HOME</span></a></li>
                       <li class='has-sub'><a href='#'><span>ADMINISTRATION</span></a>
                          <ul>
                             <li><a href='/brand'><span>BRANDS</span></a></li>
                             <li><a href='/property'><span>PROPERTIES</span></a></li>
                             <li><a href='/role'><span>ROLES</span></a></li>
                             <li class='last'><a href='/user'><span>USERS</span></a></li>
                          </ul>
                       </li>
                       <li class='has-sub last'><a href='#'><span>REPORTING</span></a>
                          <ul>
                             <li><a href='/report'><span>REPORTS</span></a></li>
                             <li class='last'><a href='/upload'><span>UPLOAD</span></a></li>
                          </ul>
                       </li>
                       <?php if(!($_SERVER['REQUEST_URI'] == '/login')){ ?>
                        <li class="logout"><a href="<?php echo $this->url('logout') ?>"><span>LOGOUT</span></a></li>
                       <?php } ?>
                    </ul>
                    
                </div>
                <?php } ?>
            </div>
        </div>
        
        <div class="container">
            <div class="main <?php if($_SERVER['REQUEST_URI'] == '/login'){ echo 'login'; } ?>">
           
                <?php echo $this->content; ?>
            </div>
            <hr>
            <footer>
                <p>&copy; 2014 - The Hotel Group</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
