<?php
$title = 'Disable user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to disable
    <?php echo $user->first_name . ' ' . $user->last_name; ?>
</p>

<?php
$url = $this->url('user', array(
    'action' => 'disable',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $user->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>