<?php

$title = 'Update User Password';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'password',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('vPassword'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();